### ISSUE TITLE
'cannot unmarshal string into Go struct field' when creating tests

### ISSUE THREAD

**Issue by tdmalone** [terraform-providers/terraform-provider-statuscake#29]
### Terraform Version
```
Terraform v0.11.13
+ provider.statuscake v0.2.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- [statuscake_test](https://www.terraform.io/docs/providers/statuscake/r/test.html)

### Terraform Configuration Files
```hcl
resource "statuscake_test" "example_test" {
  website_name = "example.com"
  website_url  = "example.com"
  test_type    = "HTTP"
  contact_id   = 146126
}
```

### Debug Output
https://gist.github.com/tdmalone/85778595e2b6159b669214448f459562

### Expected Behavior
- Resource is created
- Resource is added to state
- Terraform returns success

### Actual Behavior
- Resource is created
- Resource is _not_ added to state (confirmed by Terraform still wanting to create it on subsequent runs)
- Terraform returns `* statuscake_test.example_test: Error creating StatusCake Test: json: cannot unmarshal string into Go struct field updateResponse.InsertID of type int`

### Steps to Reproduce
1. Add above HCL to configuration
1. Run `terraform apply` and type 'yes' when prompted
1. Observe error; check app.statuscake.com to confirm that resource has created; run `terraform apply` again to observe Terraform wanting to create the test again

### Important Factoids
I'm not sure what caused this behaviour - I have been creating tests semi-regularly for some time, and first encountered this issue today. I probably last successfully did this 1-2 weeks ago so it's possible something has changed (in the StatusCake API?) in that time.

**Comment by steerben** [comment]
+1
Same here. Stopped working at some point last week.
When inserting a new test the response from the statuscake API changed.
The `InsertID` field now contains a string instead of an int. This is not reflected in the current statuscake documentation.
(https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md)

This logic handling the response is in the vendor code providing the statuscake client
https://github.com/DreamItGetIT/statuscake

Sample reponse from the api when creating a new service via curl:

```json
{
  "Success": true,
  "Data": {
    "WebsiteName": "Google",
    "WebsiteURL": "google.com",
    "CheckRate": 300,
    "TestType": "HTTP",
    "Client": "xxxx_some_number",
    "Status": "Up"
  },
  "Message": "Test Inserted",
  "InsertID": "3990147"
}
```

**Comment by ivanschwarz** [comment]
Adjusting [`updateResponse`](https://github.com/terraform-providers/terraform-provider-statuscake/blob/844b5a68d8af4791755b8f0ad293cc99f5959183/vendor/github.com/DreamItGetIT/statuscake/responses.go#L17) (`` InsertID int         `json:"InsertID,string"` ``) seems to fix it. So that's a short term workaround for people who need a working provider now.

If this is a permanent breaking change in StatusCake API, I guess a PR should be first filed in the [client](https://github.com/DreamItGetIT/statuscake) repository.

Side note: SSL test API changed too.

**Comment by steerben** [comment]
I raised the issue at Statuscake and hope they will come back with an answer soon.

**Comment by steerben** [comment]
Just a short update from the statuscake support team:

> Thanks for waiting - this has been fixed in a recent deploy and you should see things back to the way they were :)

I also verified it:

```json
{
  "Success": true,
  "Data": {
    "WebsiteName": "Google",
    "WebsiteURL": "google.com",
    "CheckRate": 300,
    "TestType": "HTTP",
    "Client": "70029",
    "Status": "Up"
  },
  "Message": "Test Inserted",
  "InsertID": 3991640
}
```
Therefore fixed.

**Comment by tdmalone** [comment]
Thanks so much for raising and getting it fixed @steerben!
